In [1]:
## READS MNQ-TICK from HGT-Export SC chartbook

In [1]:
import pandas as pd
import numpy as np
import datetime as dt 
from pathlib import Path
import time

In [2]:
# Configuration: Style preferences
#plt.style.use('ggplot') # Good default for readability
pd.set_option("display.width", 400)      # total characters per line
pd.set_option("display.max_columns", 30) # prevent wrapping by limiting columns
pd.set_option("display.max_rows", 1000)

In [3]:
import os
os.getcwd()

'/home/vm/pt/hgt-rl/mnq-tick/iteration3a'

In [6]:
#symbol = 'mnq'
#SEC = 2

#inFile = f'/mnt/d/SierraChart/data/EXPORT/MNQ-TICK-OSCILLATOR-6SEC.csv'
#outFile= f'data/mnq-tick-oscillator-6sec.pqt'
inFile = f'/mnt/d/SierraChart/data/EXPORT/MNQ-ALL-3SEC.csv'
outFile= f'data/mnq-tick-all-3sec.pqt'

print(inFile, outFile)

/mnt/d/SierraChart/data/EXPORT/MNQ-ALL-3SEC.csv data/mnq-tick-all-3sec.pqt

In [7]:
df = pd.read_csv(inFile)

print(df.info())
print(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 11021818 entries, 0 to 11021817
Data columns (total 38 columns):
 #   Column         Dtype
---  ------         -----
 0   Date           str
 1   Time           str
 2   Open           float64
 3   High           float64
 4   Low            float64
 5   Last           float64
 6   Volume         int64
 7   #ofTrades      int64
 8   OHLCAvg        float64
 9   HLCAvg         float64
 10  HLAvg          float64
 11  BidVolume      int64
 12  AskVolume      int64
 13  Open.1         float64
 14  High.1         float64
 15  Low.1          float64
 16  Last.1         float64
 17  JMA            float64
 18  VEL            float64
 19  ZeroLevel      float64
 20  VEL.1          float64
 21  ZeroLevel.1    float64
 22  RSX            float64
 23  TopLevel       float64
 24  BottomLevel    float64
 25  ZeroLevel.2    float64
 26  RSX.1          float64
 27  TopLevel.1     float64
 28  BottomLevel.1  float64
 29  ZeroLevel.3    float64
 30  Momentum       float64
 31  Line           float64
 32  Momentum.1     float64
 33  Line.1         float64
 34  Momentum.2     float64
 35  Momentum.3     float64
 36  Line.2         float64
 37  JMA.1          float64
dtypes: float64(32), int64(4), str(2)
memory usage: 3.4 GB
None
       Date             Time     Open      High       Low      Last  Volume  #ofTrades   OHLCAvg    HLCAvg     HLAvg  BidVolume  AskVolume       Open.1    High.1  ...  TopLevel  BottomLevel  ZeroLevel.2      RSX.1  TopLevel.1  BottomLevel.1  ZeroLevel.3     Momentum  Line   Momentum.1  Line.1  Momentum.2  Momentum.3  Line.2       JMA.1
0  2022-1-3  08:00:00.000000  16431.0  16431.00  16429.75  16430.25      55         55  16430.50  16430.33  16430.38         29         26  16431.00000  16431.00  ...      60.0        -60.0          0.0 -49.544018        60.0          -60.0          0.0     0.000000   0.0     0.000000     0.0    0.000000    0.000000     0.0  162.844360
1  2022-1-3  08:00:03.000000  16430.0  16430.75  16429.00  16429.25      28         28  16429.75  16429.67  16429.88         19          9  16430.75000  16430.75  ...      60.0        -60.0          0.0 -22.219265        60.0          -60.0          0.0     0.000000   0.0     0.000000     0.0    0.000000    0.000000     0.0  314.161407
2  2022-1-3  08:00:06.000000  16429.5  16430.00  16429.25  16429.25      12         12  16429.50  16429.50  16429.63          2         10  16430.25000  16430.25  ...      60.0        -60.0          0.0  -1.732940        60.0          -60.0          0.0 -6582.171875   0.0     0.000000     0.0  214.763947    0.000000     0.0  377.608307
3  2022-1-3  08:00:09.000000  16429.0  16430.00  16428.75  16429.50      28         28  16429.31  16429.42  16429.38         13         15  16429.87500  16430.00  ...      60.0        -60.0          0.0  12.695168        60.0          -60.0          0.0 -3407.253906   0.0 -3407.253906     0.0   88.885284   88.885284     0.0  403.046692
4  2022-1-3  08:00:12.000000  16429.5  16429.75  16429.25  16429.25       7          7  16429.44  16429.42  16429.50          3          4  16429.59375  16429.75  ...      60.0        -60.0          0.0  22.799923        60.0          -60.0          0.0 -1450.316406   0.0 -1450.316406     0.0   34.973572   34.973572     0.0  412.581879

[5 rows x 38 columns]

In [8]:
# expand stupid SC date like 2026-7-8 to 2026-07-08
parts = df['Date'].astype(str).str.split('-', expand=True)

year  = parts[0]
month = parts[1].str.zfill(2)
day   = parts[2].str.zfill(2)

df['Date_norm'] = year + '-' + month + '-' + day

# join date and time and convert to wall clock datetime64
df['timestamp'] = pd.to_datetime(
    df['Date_norm'] + ' ' + df['Time'].astype(str),
    utc=False,            # keep as wall clock, no timezone
    errors='raise'        # or 'coerce' if you want bad rows as NaT
)

# remove temp columns
df = df.drop(columns=['Date', 'Date_norm', 'Time'])

# make timestamp first column
col = df.pop('timestamp')
df.insert(0, 'timestamp', col)

print(df.info())
print(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 11021818 entries, 0 to 11021817
Data columns (total 37 columns):
 #   Column         Dtype
---  ------         -----
 0   timestamp      datetime64[us]
 1   Open           float64
 2   High           float64
 3   Low            float64
 4   Last           float64
 5   Volume         int64
 6   #ofTrades      int64
 7   OHLCAvg        float64
 8   HLCAvg         float64
 9   HLAvg          float64
 10  BidVolume      int64
 11  AskVolume      int64
 12  Open.1         float64
 13  High.1         float64
 14  Low.1          float64
 15  Last.1         float64
 16  JMA            float64
 17  VEL            float64
 18  ZeroLevel      float64
 19  VEL.1          float64
 20  ZeroLevel.1    float64
 21  RSX            float64
 22  TopLevel       float64
 23  BottomLevel    float64
 24  ZeroLevel.2    float64
 25  RSX.1          float64
 26  TopLevel.1     float64
 27  BottomLevel.1  float64
 28  ZeroLevel.3    float64
 29  Momentum       float64
 30  Line           float64
 31  Momentum.1     float64
 32  Line.1         float64
 33  Momentum.2     float64
 34  Momentum.3     float64
 35  Line.2         float64
 36  JMA.1          float64
dtypes: datetime64[us](1), float64(32), int64(4)
memory usage: 3.0 GB
None
            timestamp     Open      High       Low      Last  Volume  #ofTrades   OHLCAvg    HLCAvg     HLAvg  BidVolume  AskVolume       Open.1    High.1     Low.1  ...  TopLevel  BottomLevel  ZeroLevel.2      RSX.1  TopLevel.1  BottomLevel.1  ZeroLevel.3     Momentum  Line   Momentum.1  Line.1  Momentum.2  Momentum.3  Line.2       JMA.1
0 2022-01-03 08:00:00  16431.0  16431.00  16429.75  16430.25      55         55  16430.50  16430.33  16430.38         29         26  16431.00000  16431.00  16429.75  ...      60.0        -60.0          0.0 -49.544018        60.0          -60.0          0.0     0.000000   0.0     0.000000     0.0    0.000000    0.000000     0.0  162.844360
1 2022-01-03 08:00:03  16430.0  16430.75  16429.00  16429.25      28         28  16429.75  16429.67  16429.88         19          9  16430.75000  16430.75  16429.00  ...      60.0        -60.0          0.0 -22.219265        60.0          -60.0          0.0     0.000000   0.0     0.000000     0.0    0.000000    0.000000     0.0  314.161407
2 2022-01-03 08:00:06  16429.5  16430.00  16429.25  16429.25      12         12  16429.50  16429.50  16429.63          2         10  16430.25000  16430.25  16429.25  ...      60.0        -60.0          0.0  -1.732940        60.0          -60.0          0.0 -6582.171875   0.0     0.000000     0.0  214.763947    0.000000     0.0  377.608307
3 2022-01-03 08:00:09  16429.0  16430.00  16428.75  16429.50      28         28  16429.31  16429.42  16429.38         13         15  16429.87500  16430.00  16428.75  ...      60.0        -60.0          0.0  12.695168        60.0          -60.0          0.0 -3407.253906   0.0 -3407.253906     0.0   88.885284   88.885284     0.0  403.046692
4 2022-01-03 08:00:12  16429.5  16429.75  16429.25  16429.25       7          7  16429.44  16429.42  16429.50          3          4  16429.59375  16429.75  16429.25  ...      60.0        -60.0          0.0  22.799923        60.0          -60.0          0.0 -1450.316406   0.0 -1450.316406     0.0   34.973572   34.973572     0.0  412.581879

[5 rows x 37 columns]

In [11]:
'''
RangeIndex: 11021818 entries, 0 to 11021817
Data columns (total 38 columns):
 #   Column         Dtype  
---  ------         -----  
 0   Date           str    
 1   Time           str    
 2   Open           float64
 3   High           float64
 4   Low            float64
 5   Last           float64
 6   Volume         int64  
 7   #ofTrades      int64  
 8   OHLCAvg        float64
 9   HLCAvg         float64
 10  HLAvg          float64
 11  BidVolume      int64  
 12  AskVolume      int64  
 13  Open.1         float64
 14  High.1         float64
 15  Low.1          float64
 16  Last.1         float64
 17  JMA            float64
 18  VEL            float64
 19  ZeroLevel      float64
 20  VEL.1          float64
 21  ZeroLevel.1    float64
 22  RSX            float64
 23  TopLevel       float64
 24  BottomLevel    float64
 25  ZeroLevel.2    float64
 26  RSX.1          float64
 27  TopLevel.1     float64
 28  BottomLevel.1  float64
 29  ZeroLevel.3    float64
 30  Momentum       float64
 31  Line           float64
 32  Momentum.1     float64
 33  Line.1         float64
 34  Momentum.2     float64
 35  Momentum.3     float64
 36  Line.2         float64
 37  JMA.1          float64

RangeIndex: 5512771 entries, 0 to 5512770
Data columns (total 23 columns):
 #   Column        Dtype         
---  ------        -----         
 0   timestamp     datetime64[us]
 1   Open          float64       
 2   High          float64       
 3   Low           float64       
 4   Last          float64       
 5   JMA           float64     on HA Last   
 6   VEL           float64     on JMA  
 7   VEL.1         float64     adptive VEL on JMA
 8   TopBand       float64     bollinger on adaptive VEL  
 9   MiddleBand    float64     +  
 10  BottomBand    float64     +  
 11  RSX           float64     on Open (?)  
 12  RSX.1         float64     TICK RSX on Open (?)  
 13  Momentum      float64     on JMA len=2  
 14  Momentum.1    float64     on Momentum len=3  
 15  TopBand.1     float64     bollinger on Momentum.1  
 16  MiddleBand.1  float64     +  
 17  BottomBand.1  float64     +  
 18  Momentum.2    float64     on TICK JMA len=2
 19  Momentum.3    float64     on Momentum.2 len=3  
 20  TopBand.2     float64     bollinger on Momentum.3  
 21  MiddleBand.2  float64     +  
 22  BottomBand.2  float64     +

 #   Column           Dtype         
---  ------           -----         
 0   timestamp        datetime64[us]
 1   Open             float64       
 2   High             float64       
 3   Low              float64       
 4   Last             float64       
 5   JMA              float64       on HA Last   
 6   VEL              float64       on JMA  
 7   adpVEL           float64       adptive VEL on JMA
 8   bolTopAdpVEL     float64       bollinger on adaptive VEL  
 9   bolMidAdpVEL     float64       +  
 10  bolBotAdpVEL     float64       +  
 11  RSX              float64       on Open (?)  
 12  tickRSX          float64       TICK RSX on Open (?)  
 13  jmaD1            float64       momentum on JMA len=2  
 14  jmaD2            float64       momentum on jmaD1 len=3  
 15  bolTopJmaD2      float64       bollinger on jmaD2  
 16  bolMidJmaD2      float64       +  
 17  bolBotJmaD2      float64       +  
 18  tickJmaD1        float64       momentum on TICK JMA len=2
 19  tickJmaD2        float64       on Momentum on tickJmaD1 len=3  
 20  bolTopTickJmaD2  float64       bollinger on tickJmaD2  
 21  bolMidTickJmaD2  float64       +  
 22  bolBotTickJmaD2  float64       +
 23  tickJMA          float64       TICK JMA on HA Last
 '''

df.drop(columns=['Volume','OHLCAvg','HLCAvg','HLAvg','BidVolume','AskVolume', '#ofTrades',
                 'ZeroLevel','ZeroLevel.1','TopLevel','BottomLevel','ZeroLevel.2','TopLevel.1','BottomLevel.1','ZeroLevel.3','Line','Line.1','Line.2'], inplace=True) 

df.rename(columns={
    'Open': 'rawOpen',
    'High': 'rawHigh',
    'Low' : 'rawLow',
    'Last': 'rawLast',

    'Open.1': 'haOpen',
    'High.1': 'haHigh',
    'Low.1': 'haLow',
    'Last.1': 'haLast',
    
    'VEL.1': 'adpVEL',
    'TopBand': 'bolTopAdpVEL',
    'MiddleBand': 'bolMidAdpVEL',
    'BottomBand': 'bolBotAdpVEL',    
    'RSX.1': 'tickRSX',
    'Momentum': 'jmaD1',
    'Momentum.1': 'jmaD2',
    'TopBand.1': 'bolTopJmaD2',
    'MiddleBand.1': 'bolMidJmaD2',
    'BottomBand.1': 'bolBotJmaD2',
    'Momentum.2': 'tickJmaD1',
    'Momentum.3': 'tickJmaD2',
    'TopBand.2': 'bolTopTickJmaD2',
    'MiddleBand.2': 'bolMidTickJmaD2',
    'BottomBand.2': 'bolBotTickJmaD2',
    'JMA.1': 'tickJMA',
}, inplace=True)

print(df.info())
print(df.head())

<class 'pandas.DataFrame'>
RangeIndex: 11021818 entries, 0 to 11021817
Data columns (total 19 columns):
 #   Column     Dtype
---  ------     -----
 0   timestamp  datetime64[us]
 1   rawOpen    float64
 2   rawHigh    float64
 3   rawLow     float64
 4   rawLast    float64
 5   haOpen     float64
 6   haHigh     float64
 7   haLow      float64
 8   haLast     float64
 9   JMA        float64
 10  VEL        float64
 11  adpVEL     float64
 12  RSX        float64
 13  tickRSX    float64
 14  jmaD1      float64
 15  jmaD2      float64
 16  tickJmaD1  float64
 17  tickJmaD2  float64
 18  tickJMA    float64
dtypes: datetime64[us](1), float64(18)
memory usage: 1.6 GB
None
            timestamp  rawOpen   rawHigh    rawLow   rawLast       haOpen    haHigh     haLow      haLast           JMA          VEL  adpVEL        RSX    tickRSX        jmaD1        jmaD2   tickJmaD1  tickJmaD2     tickJMA
0 2022-01-03 08:00:00  16431.0  16431.00  16429.75  16430.25  16431.00000  16431.00  16429.75  16430.5000  24483.945312  -177.230743     0.0 -99.626312 -49.544018     0.000000     0.000000    0.000000   0.000000  162.844360
1 2022-01-03 08:00:03  16430.0  16430.75  16429.00  16429.25  16430.75000  16430.75  16429.00  16429.7500  20254.455078  -459.246765     0.0 -99.863556 -22.219265     0.000000     0.000000    0.000000   0.000000  314.161407
2 2022-01-03 08:00:06  16429.5  16430.00  16429.25  16429.25  16430.25000  16430.25  16429.25  16429.5000  17901.773438  -740.018799     0.0 -99.927063  -1.732940 -6582.171875     0.000000  214.763947   0.000000  377.608307
3 2022-01-03 08:00:09  16429.0  16430.00  16428.75  16429.50  16429.87500  16430.00  16428.75  16429.3125  16847.201172  -959.033081     0.0 -99.954224  12.695168 -3407.253906 -3407.253906   88.885284  88.885284  403.046692
4 2022-01-03 08:00:12  16429.5  16429.75  16429.25  16429.25  16429.59375  16429.75  16429.25  16429.4375  16451.457031 -1119.255493     0.0 -99.968834  22.799923 -1450.316406 -1450.316406   34.973572  34.973572  412.581879

In [12]:
print(f'monotonic: {df["timestamp"].is_monotonic_increasing}')

df['date'] = df['timestamp'].dt.normalize()

filtered_days = [
   '2022-01-17', '2022-07-04', '2022-11-24', '2023-01-16',
   '2023-02-20', '2023-04-07', '2023-05-29', '2023-06-19',
   '2023-07-04', '2023-09-04', '2023-11-23', '2024-02-19',
   '2024-05-27', '2024-06-19', '2024-07-04', '2024-11-28',
   '2025-01-09', '2025-07-04', '2025-09-01', '2025-11-27',
   '2026-04-03', '2026-07-09',               '2025-11-28'
]

# before 1168
days = df["date"]
all_days = days.drop_duplicates().sort_values()
print("Unique days before:", len(all_days))

df = df[
    ~df["timestamp"].dt.normalize().isin(pd.to_datetime(filtered_days))
]

# after -23 = 1145
days = df["date"]
all_days = days.drop_duplicates().sort_values()
print(" Unique days after:", len(all_days))

#

print(df.info())
print(df.head())

monotonic: True
Unique days before: 1169
 Unique days after: 1146
<class 'pandas.DataFrame'>
Index: 10907375 entries, 0 to 11021817
Data columns (total 20 columns):
 #   Column     Dtype
---  ------     -----
 0   timestamp  datetime64[us]
 1   rawOpen    float64
 2   rawHigh    float64
 3   rawLow     float64
 4   rawLast    float64
 5   haOpen     float64
 6   haHigh     float64
 7   haLow      float64
 8   haLast     float64
 9   JMA        float64
 10  VEL        float64
 11  adpVEL     float64
 12  RSX        float64
 13  tickRSX    float64
 14  jmaD1      float64
 15  jmaD2      float64
 16  tickJmaD1  float64
 17  tickJmaD2  float64
 18  tickJMA    float64
 19  date       datetime64[us]
dtypes: datetime64[us](2), float64(18)
memory usage: 1.7 GB
None
            timestamp  rawOpen   rawHigh    rawLow   rawLast       haOpen    haHigh     haLow      haLast           JMA          VEL  adpVEL        RSX    tickRSX        jmaD1        jmaD2   tickJmaD1  tickJmaD2     tickJMA       date
0 2022-01-03 08:00:00  16431.0  16431.00  16429.75  16430.25  16431.00000  16431.00  16429.75  16430.5000  24483.945312  -177.230743     0.0 -99.626312 -49.544018     0.000000     0.000000    0.000000   0.000000  162.844360 2022-01-03
1 2022-01-03 08:00:03  16430.0  16430.75  16429.00  16429.25  16430.75000  16430.75  16429.00  16429.7500  20254.455078  -459.246765     0.0 -99.863556 -22.219265     0.000000     0.000000    0.000000   0.000000  314.161407 2022-01-03
2 2022-01-03 08:00:06  16429.5  16430.00  16429.25  16429.25  16430.25000  16430.25  16429.25  16429.5000  17901.773438  -740.018799     0.0 -99.927063  -1.732940 -6582.171875     0.000000  214.763947   0.000000  377.608307 2022-01-03
3 2022-01-03 08:00:09  16429.0  16430.00  16428.75  16429.50  16429.87500  16430.00  16428.75  16429.3125  16847.201172  -959.033081     0.0 -99.954224  12.695168 -3407.253906 -3407.253906   88.885284  88.885284  403.046692 2022-01-03
4 2022-01-03 08:00:12  16429.5  16429.75  16429.25  16429.25  16429.59375  16429.75  16429.25  16429.4375  16451.457031 -1119.255493     0.0 -99.968834  22.799923 -1450.316406 -1450.316406   34.973572  34.973572  412.581879 2022-01-03

In [13]:
df.to_parquet(outFile, index=False)
print(f'written to: {outFile}')

In [18]:
print(df["timestamp"].dt.time.min())    
print(f'dates range: {df["date"].min()} .. {df["date"].max()}')    
x = 1/0

08:00:00
dates range: 2022-01-03 00:00:00 .. 2026-07-10 00:00:00

ZeroDivisionError: division by zero

In [14]:
# find out why one is larger than the other by 1 day
outFile1= f'data/mnq-tick-full-3sec.pqt'
outFile2= f'data/mnq-ohlc-raw-3sec.pqt'

df1 = pd.read_parquet(outFile1)
df2 = pd.read_parquet(outFile2)

days1 = df1['date'].unique()
days2 = df2['date'].unique()

print(len(days1), len(days2))

missing = [x for x in days2 if x not in days1]
print(missing)

1145 1145
[]

In [20]:
## WHY 3STREAM DONT MATCH BETWEEN OLD AND NEW
fsrc1 = f'data/mnq-tick-all-3sec.pqt'
fsrc2 = f'data/mnq-tick-full-3sec.pqt'
fraw = f'data/mnq-ohlc-raw-3sec.pqt'

src1 = pd.read_parquet(fsrc1)
src2 = pd.read_parquet(fsrc2)
raw  = pd.read_parquet(fraw)

In [24]:
pd.set_option('display.float_format', lambda x: f'{x:.8f}')

print(src1.head(100))
display(src2.head())
display(raw.head())

             timestamp        rawOpen        rawHigh         rawLow        rawLast         haOpen         haHigh          haLow         haLast            JMA            VEL       adpVEL          RSX       tickRSX          jmaD1          jmaD2    tickJmaD1     tickJmaD2      tickJMA       date
0  2022-01-03 08:00:00 16431.00000000 16431.00000000 16429.75000000 16430.25000000 16431.00000000 16431.00000000 16429.75000000 16430.50000000 24483.94531250  -177.23074341   0.00000000 -99.62631226  -49.54401779     0.00000000     0.00000000   0.00000000    0.00000000 162.84436035 2022-01-03
1  2022-01-03 08:00:03 16430.00000000 16430.75000000 16429.00000000 16429.25000000 16430.75000000 16430.75000000 16429.00000000 16429.75000000 20254.45507813  -459.24676514   0.00000000 -99.86355591  -22.21926498     0.00000000     0.00000000   0.00000000    0.00000000 314.16140747 2022-01-03
2  2022-01-03 08:00:06 16429.50000000 16430.00000000 16429.25000000 16429.25000000 16430.25000000 16430.25000000 16429.25000000 16429.50000000 17901.77343750  -740.01879883   0.00000000 -99.92706299   -1.73294044 -6582.17187500     0.00000000 214.76394653    0.00000000 377.60830688 2022-01-03
3  2022-01-03 08:00:09 16429.00000000 16430.00000000 16428.75000000 16429.50000000 16429.87500000 16430.00000000 16428.75000000 16429.31250000 16847.20117188  -959.03308105   0.00000000 -99.95422363   12.69516850 -3407.25390625 -3407.25390625  88.88528442   88.88528442 403.04669189 2022-01-03
4  2022-01-03 08:00:12 16429.50000000 16429.75000000 16429.25000000 16429.25000000 16429.59375000 16429.75000000 16429.25000000 16429.43750000 16451.45703125 -1119.25549316   0.00000000 -99.96883392   22.79992294 -1450.31640625 -1450.31640625  34.97357178   34.97357178 412.58187866 2022-01-03
5  2022-01-03 08:00:15 16429.75000000 16432.25000000 16429.75000000 16431.25000000 16429.51562500 16432.25000000 16429.51562500 16430.75000000 16337.26464844 -1222.96923828   0.00000000 -99.97792053   29.91169548  -509.93652344  6072.23535156  12.26113892 -202.50280762 415.30783081 2022-01-03
6  2022-01-03 08:00:18 16431.50000000 16432.00000000 16430.75000000 16431.75000000 16430.13281250 16432.00000000 16430.13281250 16431.50000000 16326.31738281 -1281.27392578   0.00000000 -99.98253632   34.99773788  -125.13964844  3282.11425781   2.64041138  -86.24487305 415.22229004 2022-01-03
7  2022-01-03 08:00:21 16432.00000000 16432.25000000 16432.00000000 16432.25000000 16430.81640625 16432.25000000 16430.81640625 16432.12500000 16345.54687500 -1309.21679688   0.00000000 -99.98308563   38.81919479     8.28222656  1458.59863281  -1.51348877  -36.48706055 413.79434204 2022-01-03
8  2022-01-03 08:00:24 16432.00000000 16432.00000000 16431.25000000 16431.25000000 16431.47070313 16432.00000000 16431.25000000 16431.62500000 16368.32031250 -1290.22558594   0.00000000 -99.97976685   44.27735138    42.00292969   551.93945313  -4.39212036   -7.03253174 409.40222168 2022-01-03
9  2022-01-03 08:00:30 16431.00000000 16431.00000000 16431.00000000 16431.00000000 16431.54687500 16431.54687500 16431.00000000 16431.00000000 16386.96875000 -1207.74511719   0.00000000 -99.97426605   46.26517105    41.42187500   166.56152344  -4.94503784   -3.43154907 406.81726074 2022-01-03
10 2022-01-03 08:00:33 16430.75000000 16431.00000000 16430.00000000 16430.50000000 16431.27343750 16431.27343750 16430.00000000 16430.56250000 16400.56250000 -1076.91479492   0.00000000 -99.96763611   49.02313232    32.24218750    23.95996094  -4.67785645   -0.28573608 402.13940430 2022-01-03
11 2022-01-03 08:00:39 16431.00000000 16432.00000000 16431.00000000 16432.00000000 16430.91796875 16432.00000000 16430.91796875 16431.50000000 16410.48242188  -921.53308105   0.00000000 -99.96041107   50.13564301    23.51367188   -18.48925781  -3.53787231    1.40716553 400.70294189 2022-01-03
12 2022-01-03 08:00:42 16431.75000000 16432.00000000 16431.50000000 16432.00000000 16431.20898438 16432.00000000 16431.20898438 16431.81250000 16417.51171875  -758.06506348   0.00000000 -99.95148468   51.34900665    16.94921875   -24.47265625  -2.61221313    2.54919434 399.52719116 2022-01-03
13 2022-01-03 08:00:45 16432.25000000 16432.25000000 16431.25000000 16431.25000000 16431.51171875 16432.25000000 16431.25000000 16431.75000000 16422.27148438  -597.26770020   0.00000000 -99.93963623   52.48159027    11.78906250   -20.45312500  -2.29348755    2.38436890 398.40945435 2022-01-03
14 2022-01-03 08:00:48 16431.50000000 16432.50000000 16430.50000000 16432.50000000 16431.63085938 16432.50000000 16430.50000000 16431.75000000 16425.43945313  -447.60998535   0.00000000 -99.92455292   53.38306427     7.92773438   -15.58593750  -2.38943481    1.14843750 397.13775635 2022-01-03
15 2022-01-03 08:00:51 16432.00000000 16432.00000000 16431.50000000 16432.00000000 16431.69140625 16432.00000000 16431.50000000 16431.87500000 16427.59179688  -316.57821655   0.00000000 -99.90593719   53.61576843     5.32031250   -11.62890625  -2.86587524   -0.25366211 395.54357910 2022-01-03
16 2022-01-03 08:00:54 16432.25000000 16432.75000000 16432.25000000 16432.50000000 16431.78320313 16432.75000000 16431.78320313 16432.43750000 16429.24609375  -210.63520813   0.00000000 -99.88253784   52.33025360     3.80664063    -7.98242188  -3.57830811   -1.28482056 393.55944824 2022-01-03
17 2022-01-03 08:00:57 16432.00000000 16432.00000000 16432.00000000 16432.00000000 16432.10937500 16432.10937500 16432.00000000 16432.00000000 16430.21484375  -134.39591980   0.00000000 -99.84913635   48.19047165     2.62304688    -5.30468750  -4.07064819   -1.68121338 391.47293091 2022-01-03
18 2022-01-03 08:01:00 16432.50000000 16432.50000000 16432.00000000 16432.00000000 16432.05468750 16432.50000000 16432.00000000 16432.25000000 16430.90234375   -84.33759308 -34.31556320 -99.80317688   40.43814468     1.65625000    -3.66406250  -3.85183716   -0.98596191 389.70761108 2022-01-03
19 2022-01-03 08:01:03 16432.75000000 16433.75000000 16432.75000000 16433.25000000 16432.15234375 16433.75000000 16432.15234375 16433.12500000 16431.70312500   -53.36456680 -24.77705002 -99.73638916   28.48095894     1.48828125    -2.31835938  -3.13018799    0.44812012 388.34274292 2022-01-03
20 2022-01-03 08:01:06 16433.00000000 16434.50000000 16433.00000000 16433.75000000 16432.63867188 16434.50000000 16432.63867188 16433.56250000 16432.45898438   -34.86869049 -11.18050480 -99.61750793   10.11275291     1.55664063    -1.06640625  -2.33609009    1.73455811 387.37152100 2022-01-03
21 2022-01-03 08:01:09 16434.00000000 16434.75000000 16434.00000000 16434.25000000 16433.10156250 16434.75000000 16433.10156250 16434.25000000 16433.22070313   -24.03566170  -2.54456806 -99.37154388  -21.13017082     1.51757813    -0.13867188  -1.76403809    2.08779907 386.57870483 2022-01-03
22 2022-01-03 08:01:12 16434.75000000 16435.50000000 16434.50000000 16435.00000000 16433.67578125 16435.50000000 16433.67578125 16434.93750000 16433.98437500   -17.74191856   1.45156264 -98.72405243  -92.94940186     1.52539063     0.03710938  -1.62356567    1.50662231 385.74795532 2022-01-03
23 2022-01-03 08:01:15 16435.00000000 16435.00000000 16434.25000000 16434.25000000 16434.30664063 16435.00000000 16434.25000000 16434.62500000 16434.35742188   -14.08233738   2.72704720 -95.46443939 -100.00000000     1.13671875    -0.41992188  -2.06756592    0.26852417 384.51113892 2022-01-03
24 2022-01-03 08:01:18 16435.25000000 16435.75000000 16435.25000000 16435.50000000 16434.46484375 16435.75000000 16434.46484375 16435.43750000 16434.82226563   -11.93398952   2.75252700 100.00000000 -100.00000000     0.83789063    -0.67968750  -2.94384766   -1.17980957 382.80410767 2022-01-03
25 2022-01-03 08:01:21 16435.50000000 16435.50000000 16434.75000000 16435.25000000 16434.95117188 16435.50000000 16434.75000000 16435.25000000 16435.07617188   -10.76872540   2.33720183 100.00000000 -100.00000000     0.71875000    -0.80664063  -3.34378052   -1.72021484 381.16735840 2022-01-03
26 2022-01-03 08:01:24 16434.75000000 16435.75000000 16434.50000000 16435.25000000 16435.10156250 16435.75000000 16434.50000000 16435.06250000 16435.11523438   -10.13668537   1.84648454 100.00000000 -100.00000000     0.29296875    -0.84375000  -2.97668457   -0.90911865 379.82742310 2022-01-03
27 2022-01-03 08:01:27 16435.50000000 16436.25000000 16435.25000000 16435.50000000 16435.08203125 16436.25000000 16435.08203125 16435.62500000 16435.25195313    -9.79386711   1.41718042 100.00000000 -100.00000000     0.17578125    -0.66210938  -2.17645264    0.76739502 378.99090576 2022-01-03
28 2022-01-03 08:01:30 16435.75000000 16436.00000000 16435.25000000 16435.50000000 16435.35351563 16436.00000000 16435.25000000 16435.62500000 16435.36914063    -9.60792255   1.08073962 100.00000000 -100.00000000     0.25390625    -0.46484375  -0.88424683    2.45953369 378.94317627 2022-01-03
29 2022-01-03 08:01:33 16435.75000000 16436.00000000 16434.75000000 16435.00000000 16435.48828125 16436.00000000 16434.75000000 16435.37500000 16435.42382813    -9.50706673   0.82857144 100.00000000 -100.00000000     0.17187500    -0.12109375   1.07089233    4.04757690 380.06179810 2022-01-03
30 2022-01-03 08:01:36 16434.75000000 16434.75000000 16434.75000000 16434.75000000 16435.43164063 16435.43164063 16434.75000000 16434.75000000 16435.38867188    -9.45236206   0.64129275 100.00000000 -100.00000000     0.01953125    -0.15625000   3.20498657    5.38143921 382.14816284 2022-01-03
31 2022-01-03 08:01:39 16434.50000000 16434.75000000 16434.25000000 16434.75000000 16435.08984375 16435.08984375 16434.25000000 16434.56250000 16435.30468750    -9.42269039   0.50004804 100.00000000 -100.00000000    -0.11914063    -0.37304688   4.75177002    5.63601685 384.81356812 2022-01-03
32 2022-01-03 08:01:42 16434.50000000 16434.50000000 16434.25000000 16434.25000000 16434.82617188 16434.82617188 16434.25000000 16434.37500000 16435.19335938    -9.40659618   0.38987461 100.00000000  -26.39846039    -0.19531250    -0.36718750   5.79757690    4.72668457 387.94573975 2022-01-03
33 2022-01-03 08:01:45 16435.00000000 16435.00000000 16433.75000000 16433.75000000 16434.60156250 16435.00000000 16433.75000000 16434.37500000 16435.06640625    -9.39786720   0.30031347 100.00000000   18.78277969    -0.23828125    -0.25781250   6.51028442    3.30529785 391.32385254 2022-01-03
34 2022-01-03 08:01:48 16434.25000000 16434.25000000 16433.50000000 16433.50000000 16434.48828125 16434.48828125 16433.50000000 16433.87500000 16434.91601563    -9.39313221   0.22450335 100.00000000   45.17184448    -0.27734375    -0.15820313   6.54003906    1.78826904 394.48577881 2022-01-03
35 2022-01-03 08:01:51 16433.50000000 16434.00000000 16433.25000000 16433.50000000 16434.18164063 16434.18164063 16433.25000000 16433.56250000 16434.73828125    -9.39056396   0.15817319 100.00000000   61.11669159    -0.32812500    -0.13281250   5.75103760   -0.04653931 397.07489014 2022-01-03
36 2022-01-03 08:01:54 16434.00000000 16434.00000000 16433.75000000 16433.75000000 16433.87109375 16434.00000000 16433.75000000 16433.87500000 16434.56445313    -9.38917160   0.09907058 100.00000000   69.78492737    -0.35156250    -0.11328125   4.38504028   -2.12524414 398.87081909 2022-01-03
37 2022-01-03 08:01:57 16433.50000000 16433.75000000 16433.00000000 16433.00000000 16433.87304688 16433.87304688 16433.00000000 16433.31250000 16434.38085938    -9.38841534   0.04638647 100.00000000   71.96638489    -0.35742188    -0.08007813   2.71722412   -3.82281494 399.79211426 2022-01-03
38 2022-01-03 08:02:00 16432.75000000 16432.75000000 16432.50000000 16432.75000000 16433.59375000 16433.59375000 16432.50000000 16432.68750000 16434.16796875    -9.38800621  -0.00017459 100.00000000   68.07761383    -0.39648438    -0.06835938   0.98947144   -4.76156616 399.86029053 2022-01-03
39 2022-01-03 08:02:03 16432.75000000 16432.75000000 16432.75000000 16432.75000000 16433.14062500 16433.14062500 16432.75000000 16432.75000000 16433.93945313    -9.38778400  -0.04086946 100.00000000   58.85390472    -0.44140625    -0.08984375  -0.63311768   -5.01815796 399.15899658 2022-01-03
40 2022-01-03 08:02:06 16434.00000000 16434.00000000 16434.00000000 16434.00000000 16432.94531250 16434.00000000 16432.94531250 16434.00000000 16433.77929688    -9.38766289  -0.07463629 100.00000000   45.46490479    -0.38867188    -0.03125000  -1.77011108   -4.48733521 398.09017944 2022-01-03
41 2022-01-03 08:02:09 16434.00000000 16434.00000000 16433.50000000 16433.75000000 16433.47265625 16434.00000000 16433.47265625 16433.81250000 16433.68359375    -9.38759804  -0.10052734 100.00000000   31.70569420    -0.25585938     0.14062500  -1.92562866   -2.91510010 397.23336792 2022-01-03
42 2022-01-03 08:02:12 16433.75000000 16433.75000000 16433.00000000 16433.00000000 16433.64257813 16433.75000000 16433.00000000 16433.37500000 16433.61914063    -9.38756180  -0.11873772 100.00000000   20.66960907    -0.16015625     0.28125000  -1.29598999   -0.66287231 396.79418945 2022-01-03
43 2022-01-03 08:02:15 16433.00000000 16433.00000000 16433.00000000 16433.00000000 16433.50781250 16433.50781250 16433.00000000 16433.00000000 16433.55078125    -9.38754272  -0.13006386 100.00000000   13.36518383    -0.13281250     0.25585938  -0.72445679    1.04565430 396.50891113 2022-01-03
44 2022-01-03 08:02:18 16433.50000000 16433.75000000 16433.50000000 16433.75000000 16433.25390625 16433.75000000 16433.25390625 16433.62500000 16433.50585938    -9.38753223  -0.13537754 100.00000000    7.87973785    -0.11328125     0.14257813  -0.51858521    1.40704346 396.27560425 2022-01-03
45 2022-01-03 08:02:21 16434.00000000 16434.25000000 16433.75000000 16434.25000000 16433.43945313 16434.25000000 16433.43945313 16434.06250000 16433.50781250    -9.38752651  -0.13497077 100.00000000    3.40621495    -0.04296875     0.11718750  -0.34948730    0.94650269 396.15942383 2022-01-03
46 2022-01-03 08:02:24 16434.00000000 16434.00000000 16434.00000000 16434.00000000 16433.75000000 16434.00000000 16433.75000000 16434.00000000 16433.54296875    -9.38752365  -0.12895021 100.00000000    0.24077320     0.03710938     0.16992188  -0.00607300    0.71838379 396.26953125 2022-01-03
47 2022-01-03 08:02:27 16433.50000000 16434.00000000 16433.50000000 16434.00000000 16433.87500000 16434.00000000 16433.50000000 16433.75000000 16433.58984375    -9.29312229  -0.11806455 100.00000000   -0.88641149     0.08203125     0.19531250   0.47628784    0.99487305 396.63571167 2022-01-03
48 2022-01-03 08:02:30 16433.75000000 16434.50000000 16433.75000000 16434.50000000 16433.81250000 16434.50000000 16433.75000000 16434.12500000 16433.64843750    -9.14244270  -0.10334606 100.00000000    0.34077501     0.10546875     0.14843750   1.14477539    1.49426270 397.41430664 2022-01-03
49 2022-01-03 08:02:33 16434.75000000 16435.25000000 16434.75000000 16435.25000000 16433.96875000 16435.25000000 16433.96875000 16435.00000000 16433.75976563    -8.95589066  -0.09536277 100.00000000    5.27699804     0.16992188     0.13281250   1.99752808    2.00360107 398.63323975 2022-01-03
50 2022-01-03 08:02:36 16435.25000000 16435.50000000 16435.25000000 16435.25000000 16434.48437500 16435.50000000 16434.48437500 16435.31250000 16433.92773438    -8.74428558  -0.09103262 100.00000000   13.88088703     0.27929688     0.19726563   2.60150146    2.12521362 400.01580811 2022-01-03
51 2022-01-03 08:02:39 16435.50000000 16435.50000000 16434.75000000 16435.25000000 16434.89843750 16435.50000000 16434.75000000 16435.25000000 16434.12500000    -8.51341629  -0.08868395 100.00000000   23.52415085     0.36523438     0.25976563   2.83694458    1.69216919 401.47018433 2022-01-03
52 2022-01-03 08:02:42 16435.00000000 16435.00000000 16434.00000000 16434.25000000 16435.07421875 16435.07421875 16434.00000000 16434.56250000 16434.29296875    -8.26667690  -0.08741003 100.00000000   33.36301804     0.36523438     0.19531250   2.84094238    0.84341431 402.85675049 2022-01-03
53 2022-01-03 08:02:45 16434.00000000 16434.00000000 16433.25000000 16433.75000000 16434.81835938 16434.81835938 16433.25000000 16433.75000000 16434.37890625    -8.00662899  -0.08539914 100.00000000   42.50667572     0.25390625    -0.02539063   2.42840576   -0.17309570 403.89859009 2022-01-03
54 2022-01-03 08:02:48 16434.00000000 16434.00000000 16434.00000000 16434.00000000 16434.28515625 16434.28515625 16434.00000000 16434.00000000 16434.39843750    -7.73590422  -0.08241855 100.00000000   48.13466644     0.10546875    -0.25976563   1.54736328   -1.28958130 404.40411377 2022-01-03
55 2022-01-03 08:02:51 16433.75000000 16433.75000000 16433.50000000 16433.75000000 16434.14257813 16434.14257813 16433.50000000 16433.68750000 16434.36132813    -7.45769262  -0.07844312 100.00000000   47.73598862    -0.01757813    -0.38281250   0.29125977   -2.54968262 404.18984985 2022-01-03
56 2022-01-03 08:02:54 16434.00000000 16434.00000000 16434.00000000 16434.00000000 16433.91406250 16434.00000000 16433.91406250 16434.00000000 16434.30078125    -7.17590952  -0.07365967 100.00000000   38.97346878    -0.09765625    -0.35156250  -0.97592163   -3.40432739 403.42819214 2022-01-03
57 2022-01-03 08:02:57 16434.25000000 16434.50000000 16433.00000000 16433.50000000 16433.95703125 16434.50000000 16433.00000000 16433.81250000 16434.23046875    -6.89511919  -0.06841578 100.00000000   25.42970848    -0.13085938    -0.23632813  -1.65884399   -3.20620728 402.53100586 2022-01-03
58 2022-01-03 08:03:00 16433.00000000 16433.00000000 16432.75000000 16432.75000000 16433.88476563 16433.88476563 16432.75000000 16432.87500000 16434.11132813    -6.62032652  -0.06318180 100.00000000   12.45293808    -0.18945313    -0.17187500  -1.78558350   -2.07684326 401.64260864 2022-01-03
59 2022-01-03 08:03:03 16433.25000000 16433.75000000 16433.25000000 16433.75000000 16433.37890625 16433.75000000 16433.25000000 16433.50000000 16433.98632813    -6.35536814  -0.05841613 100.00000000    1.23670721    -0.24414063    -0.14648438  -1.56896973   -0.59304810 400.96203613 2022-01-03
60 2022-01-03 08:03:06 16434.00000000 16434.00000000 16433.50000000 16433.50000000 16433.43945313 16434.00000000 16433.43945313 16433.75000000 16433.88281250    -6.10185194  -0.05444150 100.00000000  -12.17559242    -0.22851563    -0.09765625  -0.63290405    1.15267944 400.32913208 2022-01-03
61 2022-01-03 08:03:12 16433.75000000 16434.50000000 16433.50000000 16433.50000000 16433.59375000 16434.50000000 16433.50000000 16433.81250000 16433.81250000    -5.85925388  -0.05139091 100.00000000  -14.96407890    -0.17382813     0.01562500  -0.24337769    1.32559204 400.29483032 2022-01-03
62 2022-01-03 08:03:15 16434.00000000 16434.75000000 16433.75000000 16434.00000000 16433.70312500 16434.75000000 16433.70312500 16434.12500000 16433.78710938    -5.62544584  -0.04921805 100.00000000  -15.79044247    -0.09570313     0.14843750   0.19052124    1.29492188 400.51965332 2022-01-03
63 2022-01-03 08:03:18 16433.50000000 16433.50000000 16433.50000000 16433.50000000 16433.91406250 16433.91406250 16433.50000000 16433.50000000 16433.76757813    -5.39730453  -0.04803949 100.00000000  -13.36114883    -0.04492188     0.18359375   0.64453125    1.27743530 400.93936157 2022-01-03
64 2022-01-03 08:03:21 16433.25000000 16433.50000000 16433.25000000 16433.50000000 16433.70703125 16433.70703125 16433.25000000 16433.37500000 16433.73632813    -5.17116213  -0.04740024 100.00000000   -8.26747513    -0.05078125     0.12304688   0.60232544    0.84570313 401.12197876 2022-01-03
65 2022-01-03 08:03:24 16433.25000000 16433.25000000 16433.00000000 16433.00000000 16433.54101563 16433.54101563 16433.00000000 16433.12500000 16433.68164063    -4.94306374  -0.04705351  46.38500595   -5.68984032    -0.08593750     0.00976563  -0.09500122   -0.28552246 400.84436035 2022-01-03
66 2022-01-03 08:03:27 16433.50000000 16435.50000000 16433.50000000 16435.25000000 16433.33203125 16435.50000000 16433.33203125 16434.43750000 16433.67187500    -4.70876503  -0.04686544  12.54292774   -8.48228455    -0.06445313    -0.01953125  -0.83020020   -1.47473145 400.29177856 2022-01-03

            timestamp           Open           High            Low           Last            JMA            VEL     adpVEL  bolTopAdpVEL  bolMidAdpVEL  bolBotAdpVEL          RSX      tickRSX          jmaD1          jmaD2    bolTopJmaD2    bolMidJmaD2    bolBotJmaD2    tickJmaD1  tickJmaD2  bolTopTickJmaD2  bolMidTickJmaD2  bolBotTickJmaD2      tickJMA       date
0 2022-01-03 08:00:00 16431.00000000 16431.00000000 16429.75000000 16430.50000000 24487.08593750  -176.23469543 0.00000000    0.00000000    0.00000000    0.00000000 -99.28514862 -46.13560104     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000   0.00000000 0.00000000       0.00000000       0.00000000       0.00000000 188.34887695 2022-01-03
1 2022-01-03 08:00:03 16430.75000000 16430.75000000 16429.00000000 16429.75000000 20255.62695313  -458.66458130 0.00000000    0.00000000    0.00000000    0.00000000 -99.71918488 -27.28374863     0.00000000     0.00000000     0.00000000     0.00000000     0.00000000   0.00000000 0.00000000       0.00000000       0.00000000       0.00000000 266.11584473 2022-01-03
2 2022-01-03 08:00:06 16430.25000000 16430.25000000 16429.25000000 16429.50000000 17902.07617188  -739.60644531 0.00000000    0.00000000    0.00000000    0.00000000 -99.83817291 -27.28374863 -6585.00976563     0.00000000     0.00000000     0.00000000     0.00000000   0.00000000 0.00000000       0.00000000       0.00000000       0.00000000 266.11584473 2022-01-03
3 2022-01-03 08:00:09 16429.87500000 16430.00000000 16428.75000000 16429.31250000 16847.18359375  -959.01745605 0.00000000    0.00000000    0.00000000    0.00000000 -99.89021301 -13.55491543 -3408.44335938 -3408.44335938 -3074.02075195 -3408.44335938 -3742.86596680 126.99923706 0.00000000       0.00000000       0.00000000       0.00000000 315.34811401 2022-01-03
4 2022-01-03 08:00:12 16429.59375000 16429.75000000 16429.25000000 16429.43750000 16451.35351563 -1119.56250000 0.00000000    0.00000000    0.00000000    0.00000000 -99.91879272 -13.55491543 -1450.72265625 -1450.72265625 -2065.04980469 -2429.58300781 -2794.11621094 126.99923706 0.00000000       0.00000000       0.00000000       0.00000000 315.34811401 2022-01-03

            timestamp           Open           High            Low           Last        OHLCAvg         HLCAvg          HLAvg       date
0 2022-01-03 08:00:00 16431.00000000 16431.00000000 16429.75000000 16430.25000000 16430.50000000 16430.33000000 16430.38000000 2022-01-03
1 2022-01-03 08:00:03 16430.00000000 16430.75000000 16429.00000000 16429.25000000 16429.75000000 16429.67000000 16429.88000000 2022-01-03
2 2022-01-03 08:00:06 16429.50000000 16430.00000000 16429.25000000 16429.25000000 16429.50000000 16429.50000000 16429.63000000 2022-01-03
3 2022-01-03 08:00:09 16429.00000000 16430.00000000 16428.75000000 16429.50000000 16429.31000000 16429.42000000 16429.38000000 2022-01-03
4 2022-01-03 08:00:12 16429.50000000 16429.75000000 16429.25000000 16429.25000000 16429.44000000 16429.42000000 16429.50000000 2022-01-03